Update GettingStarted.tsx
realm/realm-studio pull request #963
Opened 2018-10-09 11:01 UTC by bmunkholm

Remove "Beta" from "Beta Forums".
Rename "Tasks" to "Todo"

2018-11-02 08:39 UTC, bmunkholm commented
@nirinchev Please review - would be good to get included in next release.

2018-11-05 06:51 UTC, bmunkholm commented
or @kraenhansen

2018-11-09 10:24 UTC, nirinchev requested changes

2018-11-12 08:35 UTC, bmunkholm commented on src/ui/ServerAdministration/GettingStarted/index.tsx
> +        'https://docs.realm.io/platform/v/3.x/getting-started/react-native-quick-start',
Not really sure. 
This is currently what works when you just goto the website: https://docs.realm.io/platform/getting-started-1/react-native-quick-start
And the others also look like this. But for some reason, they seem to redirect well enough now from the "v/3.x/", but react-native doesn't...
Seems like this should be solved at the doc level. We need to have url's that doesn't change when we include them in programs.

2018-11-12 08:37 UTC, kraenhansen commented on src/ui/ServerAdministration/GettingStarted/index.tsx
> +        'https://docs.realm.io/platform/v/3.x/getting-started/react-native-quick-start',
Should we merge with this instead?

```suggestion
        'https://docs.realm.io/platform/getting-started-1/react-native-quick-start',
```

2018-11-12 08:46 UTC, bmunkholm commented on src/ui/ServerAdministration/GettingStarted/index.tsx
> +        'https://docs.realm.io/platform/v/3.x/getting-started/react-native-quick-start',
Only if we can ensure this link lives "forever".
I'm not sure what the strategy is for those urls. Perhaps discuss this with @mgeerling in Slack #docs where we had some discussion about it.

2018-11-12 17:02 UTC, mgeerling commented on src/ui/ServerAdministration/GettingStarted/index.tsx
> +        'https://docs.realm.io/platform/v/3.x/getting-started/react-native-quick-start',
@bmunkholm if you want to ensure that this lives forever, feel free to take a look at how redirects work for gitbook as I am not going to have time to do this. 

Those are the links right now.  There is going to be a URL change in the next few months as part of this docs restructure.  After this major restructure, it is unlikely that they will change again.

2018-11-12 21:56 UTC, bmunkholm commented on src/ui/ServerAdministration/GettingStarted/index.tsx
> +        'https://docs.realm.io/platform/v/3.x/getting-started/react-native-quick-start',
@mgeerling I'll be happy to help with that. But in the context of the docs restructure project ensuring that these redirects happen needs to be part of that project. Again happy to help if I can.

2018-11-13 08:04 UTC, merged

2018-11-13 17:57 UTC, mgeerling commented on src/ui/ServerAdministration/GettingStarted/index.tsx
> +        'https://docs.realm.io/platform/v/3.x/getting-started/react-native-quick-start',
I don't know if that will be possible given that we are moving things across domains.